// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODSphereRouter.DbContexts;

#nullable disable

namespace ODSphereRouter.Migrations
{
    [DbContext(typeof(SphereRouterDbContext))]
    [Migration("20240527033042_StarSystems")]
    partial class StarSystems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("ODSphereRouter.DTOs.RouteListDTO", b =>
                {
                    b.Property<long>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.ToTable("RouteList");
                });

            modelBuilder.Entity("ODSphereRouter.DTOs.SphereDTO", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Systems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Spheres");
                });

            modelBuilder.Entity("ODSphereRouter.DTOs.StarSystemDTO", b =>
                {
                    b.Property<long>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Powers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Address");

                    b.ToTable("StarSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
